### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Kevadroz** [HelldogPack/Virtual-Reality-modpack#2]
- [ ] Testear el TFC del hasta el acero negro y todo RFTools Dimensions
- [ ] Escribir la guia de Patchouli
- [ ] Hacer 50 retoques por aqui y por alla
- [ ] Morir mucho
- [ ] Integrar varios mods por el hptweaks
- [ ] Congelar la lista de mods
- [ ] Hacer estructuras
- [ ] Meter memes de Helldog

**Comment by Marto3** [comment]
Algo me dice que esto va para largo ._.
